name: CD-ArgoCD-GitOps

on:
  push:
    branches: [ main ]
    paths:
      - 'k8s/**'

jobs:
  notify-argocd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Force ArgoCD sync (optional)
        run: |
          argocd app sync myapp --grpc-web

